name: C Project Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies on Linux
      if: runner.os == 'Linux'
      run: sudo apt update && sudo apt install -y build-essential

    - name: Build on Linux
      if: runner.os == 'Linux'
      run: make

    - name: Run tests on Linux
      if: runner.os == 'Linux'
      run: ./test/run

    - name: Setup MinGW on Windows
      if: runner.os == 'Windows'
      uses: egor-tensin/setup-mingw@v2
      with:
        version: 12.2.0
        platform: x64

    - name: Build on Windows
      if: runner.os == 'Windows'
      run: mingw32-make.exe

    - name: Run tests on Windows
      if: runner.os == 'Windows'
      run: .\test\run.exe
